### ISSUE TITLE
Adding "Window Impersonation User" | No Error Messages

### ISSUE THREAD

**Issue by saurabhgangwar** [Alchemy4Tridion/Alchemy4Tridion#126]
While adding the user, if I leave "Domain" field blank and save. Nothing happens, I guess it should show some error message.

Also if I click "Change User Info" to update the user info, leaving the "Domain" field blank and filling the other two field. On clicking save, it doesn't show any message and removes the old user info as well. I've done this testing on chrome Version 48.0.2564.97 m.

**Comment by alex-klock** [comment]
JIRA ticket A4T-37

**Comment by alex-klock** [comment]
Fixed as of version 0.8.2.
