### ISSUE TITLE
Alchemy Plugin Installation Error From Webstore Tab

### ISSUE THREAD

**Issue by domtyese** [Alchemy4Tridion/Alchemy4Tridion#127]
The user has  Alchemy Version: 0.7.0.0 and Tridion 2013SP1 on their machine. When they try to  "install" any plugin from Webstore tab of the Alchemy, the notification error shows:

![screen shot 2016-02-29 at 9 46 32 am](https://cloud.githubusercontent.com/assets/10717941/13399509/502b1e22-dec9-11e5-871b-8e729cd3372a.png)
If they try to browse 

http://localhost:81/Alchemy/api/webstore/plugins/56a615dee4de0210c46f648e/versions/1.0.0.0/install which is returning 500 internal server error, it  gives the below response:

<Error>
<Message>
The requested resource does not support http method 'GET'.
</Message>
</Error>

Looks like it doesn't support GET.

Any idea, what could be the issue?

**Comment by alex-klock** [comment]
I have not been able to reproduce this... any additional info?

**Comment by alex-klock** [comment]
I believe this issue was tracked by our PM system as one of the install plugin bugs and fixed as of 0.8.1 release.
