### ISSUE TITLE
SDL Tridion Alchemy Plugin Installation Error

### ISSUE THREAD

**Issue by domtyese** [Alchemy4Tridion/Alchemy4Tridion#128]
User is currently working on SDL Tridion 2013 SP1 and Alchemy4Tridion Version: 0.7.0.0 

The user has also downloaded the Alchemy4Tridion Developer Pack link and trying to install the demo version plugin but getting error 

![screen shot 2016-02-29 at 9 51 40 am](https://cloud.githubusercontent.com/assets/10717941/13399645/0564443a-deca-11e5-931c-24009864d9f2.png)

Error in Debugger

http://domain.com/Alchemy/api/Plugins/Install Status Code :500 Internal Server Error

Debugger Log {message: "An error has occurred.",…}
exceptionMessage:"Value cannot be empty.
 Parameter name: userName."
exceptionType:"System.ServiceModel.FaultException1[[Tridion.ContentManager.CoreService.Client.CoreServiceFault, Tridion.ContentManager.CoreService.Client, Version=7.1.0.1290, Culture=neutral, PublicKeyToken=ddfc895746e5ee6b]]" message:"An error has occurred." stackTrace:" Server stack trace: at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc) at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout) at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation) at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg) at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type) at Tridion.ContentManager.CoreService.Client.ISessionAwareCoreService.Impersonate(String userName) at Alchemy4Tridion.Plugins.Clients.AlchemySessionAwareCoreServiceClient.Impersonate(String username) at Alchemy4Tridion.Core.Web.RequestPropertiesContext.get_SessionAwareCoreServiceClient() at Alchemy4Tridion.Core.Web.RequestPropertiesContext.get_User() at Alchemy4Tridion.Core.Security.AlchemyAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) at System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
 at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"

**Comment by alex-klock** [comment]
Closing as no other info has been added and issue has not came up.

Marking as complete as of 0.8.2.
