### ISSUE TITLE
Alchemy Web Store Has no option for resetting/ retrieving password

### ISSUE THREAD

**Issue by paceaux** [Alchemy4Tridion/Alchemy4Tridion#132]
I went to the webstore for the first time in a while, and I was greeted with a modal window that wanted me to log in. 

I forgot my password, but there was no option for resetting or retrieving my password. The only two options are login and register. 

If the user presents an incorrect password too many times (or even once), please present an option to reset or retrieve the password.

**Comment by alex-klock** [comment]
Fixed and deployed this week for 0.8.3 pushes.
