### ISSUE TITLE
Restrict the user login to Alchemy Webstore

### ISSUE THREAD

**Issue by tridionvisitor** [Alchemy4Tridion/Alchemy4Tridion#137]
How We can control on user login to webstore from Tridion, Is there a way to restrict the user login other than approved.

After we Install Alchemy4Tridion, by default all the users can able to view alchemy and install/uninstall the plugins who has web store account. Instead in current approach, I am trying to restrict the users to access alchemy, based on users who have access to alchemy I wanted to give further Install,uninstall and Configure permissions

**Comment by joshhebb** [comment]
Good question. So currently all of the functionality that you mentioned exists in A4T, except for hiding the webstore from a group of users entirely; although it is on our backlog. 

If you open the control room, and navigate to "Alchemy Permissions" you can restrict which users / groups can install, uninstall and configure plugins. By default, all users have the required permissions - however once a user / group has been added to the list, all others who have not yet been added, will lose their permissions. 

![image](https://cloud.githubusercontent.com/assets/3137946/22360060/e5bff6ce-e422-11e6-8e3b-ef2229b24ac1.png)

**Comment by tridionvisitor** [comment]
Hi Josh

Thanks for reply,

Tried to repro this following statement " however once a user / group has been added to the list, all others who have not yet been added, will lose their permissions" , I see that System Admins didn't lose their permissions,is there a way to handle only some specific system admins can access ?

**Comment by Josh-Hebb** [comment]
I'm not sure I understand your question. Are you asking if there's an explicit way to disable a CM Administrator from installing plugins, even if they're in a group that's not been granted installation permissions? I believe this is true; Administrators would have full access & currently there is no way OOTB with A4T to disable their permissions, as you could simply remove their Admin access. With that said, although an edge case - I think it's a valid request, and I will add the ticket to our backlog to be prioritized. 

Let me know if you have any follow-up questions, & if not I will close the ticket.
