### ISSUE TITLE
Update Alchemy4Tridion package inside Nuget

### ISSUE THREAD

**Issue by qchen11** [Alchemy4Tridion/Alchemy4Tridion#138]
Inisde Nuget, the Alchemy4Tridion package only has version 1.0.0-beta6-1, which has no AttachToView method inside ResoureGroup. Without this we couldn't made a popup dialog to work with Tridion data together. 

Please help to update the Nuget package and reference version 1.0.0-beta8-3 or the latest version.

**Comment by HaraldHoffelinck** [comment]
Please check the nuget page here : https://www.nuget.org/packages/Alchemy4Tridion.Plugin/. The nuget releases do contain the latest version, not only beta 6.1.

you should be able to update the nuget package from your visual studio
