### ISSUE TITLE
possible to install the same plug in twice, which breaks gui

### ISSUE THREAD

**Issue by sponegg** [Alchemy4Tridion/Alchemy4Tridion#14]
it's possible to re-install a plug in that you already have.   if you do so, it fails cause it already exists, but the tridion config has already been updated causing the cms to break.

**Comment by alex-klock** [comment]
Adding the following to try to catch all cases where installed symbols may be left behind:

1.) If folder with plugin name exists, consider already installed.
2.) If installing and config elements exist from the plugin, remove them then add all config from install.
3.) On install and IIS fails to recycle, don't consider it a failed install.
