### ISSUE TITLE
Uninstall fails on first click

### ISSUE THREAD

**Issue by rsleggett** [Alchemy4Tridion/Alchemy4Tridion#17]
When uninstalling from the Alchemy CME, the uninstall seems to consistently fail on the first try but then succeed on the second (this was installed via drag and drop)

**Comment by alex-klock** [comment]
Keeping this one open but not attaching to milestone... I believe it may be due to one of the other issues fixed for 0.4.2 but we'll keep an eye to see if this continues to happen.

**Comment by alex-klock** [comment]
Closing issue as I believe this was resolved with 0.4.2 and haven't heard any updates.  Will open new issue if anything else is found during plugin uninstalls
