### ISSUE TITLE
Multiple installations cause duplicate key sequence error

### ISSUE THREAD

**Issue by eserghie** [Alchemy4Tridion/Alchemy4Tridion#2]
When installing the same plugin multiple times (unsuccessfully), the install can result in "There is a duplicate key sequence error".
This is due to multiple entries added to the "AlchemyEditor.config" file.
A temporary workaround is to remove all but the last config entry for that same plugin inside the "AlchemyEditor.config", in the Tridion\web\Alchemy\Configuration\ folder.

![image](https://cloud.githubusercontent.com/assets/11630609/8181524/908ba464-13f4-11e5-9432-44380d1beb88.png)

**Comment by alex-klock** [comment]
Updated process flow and validation so that the scenario where some symbols of an uninstalled plugin were left behind will no longer happen.  Will be in the 0.4.2 release.
