### ISSUE TITLE
Plugin versions in REST API

### ISSUE THREAD

**Issue by jhorsman** [Alchemy4Tridion/Alchemy4Tridion#20]
[enhancement]
It would be nice to have the version number of the A4Tplugins in the api/Plugins call
Currently http://hostname/Alchemy/api/Plugins only returns a list with names, the version id might be easy to add and would be very useful to determine whether or not to install a new version of the Plugin.

I will update https://github.com/jhorsman/Install-A4T-Plugin with a version number check if you can add the current plugin version in the REST API/

**Comment by alex-klock** [comment]
As discussed in Skype, will add the version number and the versionId to the data returned.  For plugins that have not been uploaded to the webstore yet, these will not have version info and will be considered as "developer builds".  Developer builds will trump any version that is already installed.  Planned for 0.4.2 release.

**Comment by alex-klock** [comment]
With release of 0.4.2, api/Plugins items will now contain versionId (the id of the version in the webstore, prob not much use to your script) and versionNumber (ie 1.20.2.4).
