### ISSUE TITLE
Link to Alchemy Plugins tab

### ISSUE THREAD

**Issue by jhorsman** [Alchemy4Tridion/Alchemy4Tridion#23]
[enhancement]
It would be great if the Alchemy GUI has a direct link to the Plugins tab. 
Something like http://localhost/SDL/#app=wcm&entry=alchemy&view=plugins or so

Also when in the Plugins tab the tab title should be clickable to refresh the tab.

**Comment by alex-klock** [comment]
0.4.2 now has the Plugins as the default tab, so /SDL/#app=wcm&entry=alchemy will point to it.
