### ISSUE TITLE
/#/about link doesn't render content

### ISSUE THREAD

**Issue by marksaunders** [Alchemy4Tridion/Alchemy4Tridion#27]
Selected from navigation pane on right, from content 'Learn More' link on landing page (after login) and in URL directly

**Comment by alex-klock** [comment]
I think you just had extremely bad timing... I just added the About in the right nav about an hour ago as final touches for 0.4.2 and deployed to server (deploy takes some time) so I think from the timing of your report you must've clicked the link before all the files had finished. :) The full deploy takes 5-20 mins depending on my connection.
