### ISSUE TITLE
AddSeperator(id) is misspelled and adds an empty block instead of a separator

### ISSUE THREAD

**Issue by bkoopman** [Alchemy4Tridion/Alchemy4Tridion#3]
On the ContextMenuExtension, AddSeperator(id) is misspelled and adds an empty block instead of a separator. 

It should be called: AddSeparator(id)

**Comment by alex-klock** [comment]
Fixing to AddSeparator() (and the type in config being "separator" too).  Will cause breaking change. Push for 0.4.2 release.
