### ISSUE TITLE
Dependencies.AddAlchemyCore() is missing in the ResourceGroup example

### ISSUE THREAD

**Issue by bkoopman** [Alchemy4Tridion/Alchemy4Tridion#4]

**Comment by alex-klock** [comment]
Added commented out section for Dependencies.AddAlchemyCore() in the HelloWorld example project and nuget project.  Describes when its necessary to use AddAlchemyCore in comments (if you're not using any of the other dependency libraries and not using the proxy but still need the alchemy scripts available to your plugin).
