### ISSUE TITLE
Download Plugin(s) results in 24 Digit Hex String error on 1.0.0.0

### ISSUE THREAD

**Issue by marksaunders** [Alchemy4Tridion/Alchemy4Tridion#47]
When clicking download button the error shown below is returned.

Error occurs in at least the plugin shown and Find and Replace, using latest version of Chrome.

![image](https://cloud.githubusercontent.com/assets/572488/8437007/9fe826f8-1f5c-11e5-8646-cc43ccf22c53.png)

**Comment by alex-klock** [comment]
Issue was that the Version links where using the Version #'s and a recent update to the api controller's was expecting the versionId's.

Updated UI to reflect backend changes.
