### ISSUE TITLE
Unable to reset password

### ISSUE THREAD

**Issue by marksaunders** [Alchemy4Tridion/Alchemy4Tridion#49]
Emails a reset option, selected but just plain homepage (without logging in / options to reset) is presented.

**Comment by alex-klock** [comment]
Thanks, looks like we forgot to update the email templates after switching to html5 mode in https://github.com/Alchemy4Tridion/Alchemy4Tridion/issues/48, so the email being sent for password reset (and registration email verification!) had the old /#/password/reset link vs just /password/reset.

Updated and deployed the email templates to the webstore.
