### ISSUE TITLE
Failure to install caused by plugin default name 

### ISSUE THREAD

**Issue by eserghie** [Alchemy4Tridion/Alchemy4Tridion#5]
Plugin failed to install if "name" field in a4t.xml file was not set to appropriate value, in our specific case "MetaDataSourceTab".

![image](https://cloud.githubusercontent.com/assets/11630609/8181672/0ba27da2-13f6-11e5-8acf-c7703a5730fc.png)

**Comment by alex-klock** [comment]
Added name check at compile time so if name is not valid error message will display in "Errors" and link to a4t.xml file to correct.  .a4t plugin file will not be created until valid name is entered.  Will be in 0.4.2 release.
