### ISSUE TITLE
Do not remove output assembly on build in package step

### ISSUE THREAD

**Issue by BjornVanDommelen** [Alchemy4Tridion/Alchemy4Tridion#60]
Currently when the package is built by Alchemy4Tridion.Plugin.targets this removes the original output DLL making it impossible to e.g. run unittests (as the test project would depend on the output DLL).

**Comment by BjornVanDommelen** [comment]
As a workaround I am using a dedicated configuration (Unittest) which sets a property
`<AlchemyPackage>Skip</AlchemyPackage>`

I've updated the condition on the target import to  
`Condition="$(AlchemyPackage)!='Skip' And Exists('..\packages\Alchemy4Tridion.Plugin.1.0.0-alpha5-0\build\net40\Alchemy4Tridion.Plugin.targets')"`

All modifications in the project file only.

**Comment by BjornVanDommelen** [comment]
Nicer solution is probably to pick up a defined constant as these can be configured in the GUI of visual studio:
`Condition="!$(DefineConstants.Contains('SkipAlchemyPackage'))"`

**Comment by alex-klock** [comment]
Added a hybrid of your two suggestions... the NuGet 0.6 package now adds a new property, AlchemyRemoveBuildFiles, which can be of values NonProjectAssembly (default), None, or All.  

NonProjectAssembly - removes all but the direct assembly output files (YourFile.dll, YourFile.xml, YourFIle.pdb, YourFile.a4t, etc).

All - behavior of pre 0.6, everything but the a4t file is removed.

None - no files are removed.

Besides editing the csproj file directly, you can also now add a define constant of `AlchemyRemoveBuildFiles=<VALUE>;` A DefineConstant will override any value that is in the <AlchemyRemoveBuildFiles> element of the csproj file.

Values are not case sensitive.

Any unrecognized value (or missing property) will result in the default NonProjectAssembly behavior.

**Comment by bvdommelen** [comment]
When I add a define constant "AchemyRemoveBuildFiles=None" I get an error from visual studio during compilation:  
`Warning    1   The parameter to the compiler is invalid, '/define:AlchemyRemoveBuildFiles=None' will be ignored.`

**Comment by alex-klock** [comment]
It works but I wasn't paying attention to the warning, is there a specific way to add a key=value type define constant w/o it throwing a warning? 

The Build Task is actually doing the parsing of the key so the warning does not have any affect, but it can be confusing/annoying.

If there's no way I may just put a notice to ignore the warning... the DefineConstant method is a temporary workaround to allow you to modify the setting w/o unloading the project and modifying the .csproj... a future release will have a better mechanic for modifying any related A4T msbuild properties.

**Comment by BjornVanDommelen** [comment]
Defined constants are semantically identical to `#define` statements in c# code and are explicitly for the use of the compiler; in essence we are abusing this feature to pass custom configuration data to our build processor which is not a totally uncommon solution I would expect but it does trip over the = character as a separator. 

Maybe the simplest solution is to use an underscore to separate the name and value of the key value pair? I don't get any warnings from VS that way: `AlchemyRemoveBuildFiles_None`

**Comment by alex-klock** [comment]
Looks good, I went with the Underscore way!
