### ISSUE TITLE
Multiple screenshots uploaded for plugin

### ISSUE THREAD

**Issue by mtrl** [Alchemy4Tridion/Alchemy4Tridion#73]
I attempted to upload a screenshot that was > than the allowed dimensions. On saving the plugin updates the screenshot did not appear to have been uploaded so I resized and retried. I did this three times and as a result the plugin (DXA_Page_Preview) now has four screenshots.

Screenshot: https://www.dropbox.com/s/my6zihvwv26n7il/Screenshot%202015-07-29%2015.12.49.png?dl=0

**Comment by alex-klock** [comment]
A redirect to the manage page was just added (you may need to clear cache) so you won't be able to have that issue happen again.

For the screenshots, #42 is still open (awaiting someone with some design skills on how the functionality should look)
