### ISSUE TITLE
Top Category has no plugins

### ISSUE THREAD

**Issue by marksaunders** [Alchemy4Tridion/Alchemy4Tridion#75]
![image](https://cloud.githubusercontent.com/assets/572488/8984782/dc81287e-36a1-11e5-9cf2-186cadd0510d.png)

**Comment by marksaunders** [comment]
If the 'top' plugins are determined by QTY of plugins with that tag, perhaps having the QTY aside the title might be a nice 'add' also?

**Comment by alex-klock** [comment]
Featured Categories wasn't actually based on anything... it was just the order that was inserted in the database.  Updated to actually go off of downloads now (downloads of top downloaded plugins).  Change has been deployed to the Webstore but won't be in A4T until 0.6.1.
