### ISSUE TITLE
Plug in names

### ISSUE THREAD

**Issue by sponegg** [Alchemy4Tridion/Alchemy4Tridion#8]
it's not possible to have spaces ' ' in the plug in name.  this isn't very readable and can break the interface design as we can get some long plugin names and that html can't wrap.

**Comment by alex-klock** [comment]
Added more validation on names... now alphanumeric, underscores, and spaces (note that spaces gets converted to "_" under the hood, and for display purposes any "_" should be displayed as spaces).
