### ISSUE TITLE
Revoke review

### ISSUE THREAD

**Issue by Guzzter** [Alchemy4Tridion/Alchemy4Tridion#92]
Hi,

Just fixed a bug in my plugin, but cannot update it in the webstore, since it's under review. Maybe it's good to have the option the revoke a review request?

Anyway: can you reset the state for GoToOwningPublication plugin?

Thanks,
Guus

**Comment by alex-klock** [comment]
Hi Guus!

I went ahead and canceled the review so its back in development status! There currently is an option to revoke but its a web store only feature (currently can't be done from VS), and its only on the actual Edit Plugin Version page so probably not the most straight forward to get to.

![image](https://cloud.githubusercontent.com/assets/5556778/9605989/d6ff3eb6-508e-11e5-9680-c3ad2cc8602a.png)

I'll leave this open as we're somewhat remodeling the review system right now, and we'll make sure to make it easier to manage / modify your plugins currently in review (and possibly be able to revoke from the Upload Dialog as well).

**Comment by Guzzter** [comment]
Thanks for pointing that out.. I will update my plugin and submit it for review later..

BTW, I don't know if this is correct channel: I really appreciate the work and effort you're putting into this. Superb!

**Comment by alex-klock** [comment]
This is a good channel for items like this, anything to do with potential issues/bugs, missing features, or new feature requests (so if there's anything you'd like to see feel free to add it as a new issue)! :)

**Comment by alex-klock** [comment]
Attaching to 0.8 milestone, this issue is directly related to #111
