### ISSUE TITLE
Alchemy Webstore does not let me login after registering

### ISSUE THREAD

**Issue by jsuurd** [Alchemy4Tridion/Alchemy4Tridion#97]
After providing password it does not accept same password when trying to log in. Tried resetting password twice and shortening it from 16 to 8 characters.

**Comment by alex-klock** [comment]
Attempting to reproduce, which browser are you using? Any special characters that you are using? (if you're not comfortable mentioning anything here feel free to skype me at alex.klock as well). If nothing stands out as to what could have caused the issue I'll try deleting the account to allow you to re-register... I'm guessing right now that maybe its a special character that maybe is getting encoded wrong in the db during encryption...

**Comment by jsuurd** [comment]
Indeed issue appears related to special characters in the password. After choosing a different password it works for me. Am able to reproduce the issue when choosing a password with the $-sign in it.

**Comment by alex-klock** [comment]
Thanks for the additional info and time on Skype to further debug! Found the issue was related to the way URI encoding/decoding was being handled. Although this task is marked for the 0.7 release this fix was pre-pushed to the server (may require a cache clear).

Thanks again! :)
